_target_: kod.core.anchors.info.AnchorBoxInfo
stride: 16
boxes_wh:
  - _target_: kod.core.types.FeatureShape
    width: 30
    height: 61
  - _target_: kod.core.types.FeatureShape
    width: 62
    height: 45
  - _target_: kod.core.types.FeatureShape
    width: 59
    height: 119
  
